### PR TITLE
Add admin page for Scheduler model

### LINKED ISSUE #68: GSoC 2019 - Scheduled tasks status page
This issue is to create a page on the admin panel that lets you see the status of all scheduled items. 

The page would display all of these fields in a table, as well as need to have basic sorting and filtering options.
```Python
    command = models.CharField(name='command', max_length=20, choices=commands)
    data = models.TextField(name='data')
    success = models.BooleanField(name='success', null=True)
    last_error = models.TextField(name='last_error', null=True, default=None)
    created = models.DateTimeField(auto_now_add=True)
```

### PR DESCRIPTION
**Pull request by sounak98**
# Description

This adds an admin page for listing all the Scheduler objects.

Fixes #68 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Screenshot 2019-03-22 at 12 14 01 AM

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have not added a commit to any .db files as part of my pull request
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by botanicvelious** [comment]
- [ ] This branch has conflicts that must be resolved

**Comment by sounak98** [comment]
@botanicvelious the conflicts have been resolved. Please check!

**Comment by sounak98** [comment]
Also the Scheduler link in the toolbar has been added in the latest commit.

**Comment by botanicvelious** [comment]
my laptop decided to die and I am out of town for a week or so I can check this when I get back =/

**Comment by botanicvelious** [comment]
looks good

**Pull request merged**
