### PR TITLE
All blogs

### LINKED ISSUE #34: GSoC 2019 - Create Page For All Blogs
For this issue, you will need to add a few blogs to the system. There is an example "Student Blogs" page already. you can add more by following [https://aldryn-newsblog.readthedocs.io/en/latest/how-to/apphook_configurations.html](https://aldryn-newsblog.readthedocs.io/en/latest/how-to/apphook_configurations.html).

Additionally you will need to add some users that are assigned to the "students" group and have a suborg and year set on them.

This task is to make a single page that displays all blogs on the system together by year. An example would be something like [https://blogs.python-gsoc.org/](https://blogs.python-gsoc.org/) for each year, newest to oldest

### PR DESCRIPTION
**Pull request by sounak98**
# Description

Creates a separate app for displaying all blogs and also archived blogs of previous years' GSoC.

Need to create a page and should be linked to this app using an `AppHook`. `<page-url>/` will display all the blogs of current GSoC and `<page-url>/archive/<year>/` will give GSoC blogs for the year `<year>`.

Preferably all the pages which are hooked to `NewsBlog`s should be removed from the menu and this page which hooks to the `blogs_list` app should be displayed on the menu.

Fixes #34 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Screenshot 2019-04-06 at 10 11 59 PM

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have not added a commit to any .db files as part of my pull request
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sounak98** [comment]
@botanicvelious have a look!

**Comment by ghost** [comment]
Cool! i'll create a page for all posts :D

**Comment by sounak98** [comment]
> Cool! i'll create a page for all posts :D

@ntkomata all posts? What do you mean?

**Comment by ghost** [comment]
> > Cool! i'll create a page for all posts :D
> 
> @ntkomata all posts? What do you mean?

it's confidential :ice_cream:

**Comment by sounak98** [comment]
Screenshot 2019-04-07 at 5 33 09 PM

@botanicvelious I think this is what we want!

**Comment by gideononyewuenyi** [comment]
i will be working on this

**Pull request merged**
