### PR TITLE
Cleared Timezone bug

### LINKED ISSUE #58: UnboundLocalError at schedule page
**Describe the bug**
The error is occurring on visiting the [Schedule page](http://localhost:8000/en/schedule/).

**To Reproduce**
1. Go to '[Schedule page](http://localhost:8000/en/schedule/).'

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Fedora 27
 - Browser: Mozilla Firefox Developer Edition 66.0b12

**Additional information**
Timezone: UTC+4

### PR DESCRIPTION
**Pull request by MastersAbh**
Fixes #58

### CODE REVIEW

**Comment by MastersAbh** [comment]
@Gouravchawla , just check if your system time is UTC+0.0 ?

**Comment by dotgourav** [comment]
@MastersAbh Thanks for taking this up. It would be great if you could put comments as well as docstring in the function explaining the logic.

Also, you need to make changes to adhere to PEP8 guidelines. Refer: https://www.python.org/dev/peps/pep-0008/

**Comment by dotgourav** [comment]
> #58

Be a little more verbose in your PR description as it will go in the git logs. You could have mentioned `Fixes #58` instead of just `#58` which doesn't mean anything on its own.

**Comment by MastersAbh** [comment]
Thanks @Gouravchawla for the advices. I'll take care from the next time.

**Pull request merged**
