### PR TITLE
Toolbar add student button

### LINKED ISSUE #33: GSoC 2019 - Add Student Menu Form
issue #37 is related

We need to have an admin menu item for adding students to the platform. 

The admin toolbar item would need to have the following

1) Form for adding students with the following fields, email, name, project, suborg, year and all fields required to be filled in
2) A "+" for adding more than one student at a time in a form list.
3) The suborg and year would be selectable from the current model as a dropdown
4) After submitting the form it would add a user with those settings for each item in the form list

### PR DESCRIPTION
**Pull request by ghost**
Fixes #33

### CODE REVIEW

**Comment by botanicvelious** [comment]
A few things

1. The add user should send an custom registration url to the users email via the custom urls using the set settings.
2. Would be best if the ui was horizontal so its easier to mass add
3. Dont need the name of the student or the username, those can be set with the custom registration url when the user logs in etc
4. changing urls.py should not be needed, see the scheduler page
5. id say put the menu item between "users settings" and "disable toolbar" in the main dropdown

**Comment by ghost** [comment]
@botanicvelious uhh ok working on it

**Comment by ghost** [comment]
@botanicvelious  Do we have a scheduler page yet?

**Comment by botanicvelious** [comment]
The scheduler page was just an example of how to avoid using urls.py, you should see it on the menu.

**Comment by ghost** [comment]
ohhhhhh yes thanks

**Comment by ghost** [comment]
@botanicvelious You mean add a model and customize admin page and use admin_reverse to get the URL?

**Comment by botanicvelious** [comment]
yup

**Comment by botanicvelious** [comment]
also itl need to add the blog page with proper permissions 💃

**Comment by ghost** [comment]
@botanicvelious ya right and I think I should also change RegLink :dancer:

**Comment by ghost** [comment]
@botanicvelious Please check!

**Comment by ghost** [comment]
@botanicvelious Still working on permission issues...

**Comment by ghost** [comment]
@botanicvelious I'm creating blog page and right permissions for each registered user. Maybe we should schedule a reload? since the blog page urls won't work right if we don't reload :)

**Pull request merged**
