### PR TITLE
Added SubOrg and GsocYear model [WIP]

### PR DESCRIPTION
**Pull request by shashank-sharma**
Solves #4 Issue

I am not sure if the implementation is correct or not so please review.

Expected outcome:
screenshot from 2019-02-12 02-52-48

### CODE REVIEW

**Comment by shashank-sharma** [comment]
Update:
Ability to add gsoc year and suborg through admin panel. I updated settings.py file for gsoc app to default db.
@botanicvelious Can you please check :)

**Comment by botanicvelious** [comment]
Looks like a step in the right direction however on the admin page the input is plain text, rather than selecting the data from a dropdown that is populated from the database.

**Comment by shashank-sharma** [comment]
@botanicvelious by "selecting the data from a dropdown" are you referring to year or present suborg?

**Comment by botanicvelious** [comment]
Both, it looks like are each a plain text field, so the database may have for example "2018, 2019" but I could type in 3019 rather then selecting from the valid list of items.

**Comment by shashank-sharma** [comment]
@botanicvelious Can you please check now, after migrating and adding year + suborg name in database you can select it as:

screenshot from 2019-02-13 17-01-53

**Comment by botanicvelious** [comment]
Looks good!

**Pull request merged**
