### PR TITLE
add upload accepted proposal  button

### PR DESCRIPTION
**Pull request by ghost**
I created 3 columns on UserProfile: is_student, is_student_accepted and accepted proposal pdf. 

If the user is student and accepted student, then the user, after logging in, can upload his proposal on Students page.

The user will be prompted for the first time if the user try to upload a pdf file.

Then the server will check the pdf file using regex. The user will be prompted the second time if django managed to find some private data.

### CODE REVIEW

**Comment by botanicvelious** [comment]
<Botanic> dont comit the project.db
<Botanic> also put the button in the user settings page
<Botanic> so when you goto your own profile you upload it there
<Botanic> 'is_student_accepted' isnt needed
<Botanic> there is the built in one
<Botanic> also dont commit migrations please

**Comment by ghost** [comment]
OK. Thanks for your advice!

**Comment by ghost** [comment]
@botanicvelious Made required changes. Have a look!

**Review by botanicvelious — CHANGES_REQUESTED** [review]
- [ ] PDFminer.six isnt included in requirements.txt
- [ ] chardet isnt in requirements.txt
- [ ] it takes any filetype not just .pdf
- [ ] Why is there a clear and a delete? https://i.imgur.com/l4MDnJ2.png
- [ ] Phone number regex seems broken
> Why not just add a validator for "phone numbers" so we can easly add more checks in the future for other international phone number syntax etc?
- [ ] email regex looks broken try EmailValidator() in django
- [ ] Why have myprofile.html at all? There is the built in "Home › Authentication and Authorization › Users" page already? However, I suppose if you direct the user to this page on the first log in there may be some value to it. Maby add a "profile complete" field and if you "are student" but not "profile complete" it directs you here to complete your profile when you goto a page?
- [ ] Redirecting to /clear_accepted_proposal_pdf/ seems a really strange way to handle this, may be better to upload with ajax and return a confirm, then based on that save it if accepted, rather then redirect to a erase page.
- [ ] Delete does not remove it from the media folder.

**Comment by ghost** [comment]
Ok......I'll make some changes

**Comment by ghost** [comment]
> * [ ]  PDFminer.six isnt included in requirements.txt
> * [ ]  chardet isnt in requirements.txt
> * [ ]  it takes any filetype not just .pdf
> * [ ]  Why is there a clear and a delete? https://i.imgur.com/l4MDnJ2.png
> * [ ]  Phone number regex seems broken
> 
> > Why not just add a validator for "phone numbers" so we can easly add more checks in the future for other international phone number syntax etc?
> 
> * [ ]  email regex looks broken try EmailValidator() in django
> * [ ]  Why have myprofile.html at all? There is the built in "Home › Authentication and Authorization › Users" page already? However, I suppose if you direct the user to this page on the first log in there may be some value to it. Maby add a "profile complete" field and if you "are student" but not "profile complete" it directs you here to complete your profile when you goto a page?
> * [ ]  Redirecting to /clear_accepted_proposal_pdf/ seems a really strange way to handle this, may be better to upload with ajax and return a confirm, then based on that save it if accepted, rather then redirect to a erase page.
> * [ ]  Delete does not remove it from the media folder.

The "DELETE?" column in that picture seems to be a django built-in, to delete a UserProfile object. :)

**Comment by ghost** [comment]
* [x]  PDFminer.six isnt included in requirements.txt
* [x]  chardet isnt in requirements.txt
> Now they are.
* [x]  it takes any filetype not just .pdf
> Now it checks on the backend and only takes pdf files.
* [ ]  Why is there a clear and a delete? https://i.imgur.com/l4MDnJ2.png
> Those two buttons seem to be django built-in.
* [x]  Phone number regex seems broken
* [x]  email regex looks broken try EmailValidator() in django
> EmailValidator only seems to validate email itself but not a chunk of text, so I used RegexValidator,
and made a small loop, to loop validating the text using validators
* [ ]  Why have myprofile.html at all? There is the built in "Home › Authentication and Authorization › Users" page already? However, I suppose if you direct the user to this page on the first log in there may be some value to it. Maby add a "profile complete" field and if you "are student" but not "profile complete" it directs you here to complete your profile when you goto a page?
> The built in profile page is django admin page and I haven't figured out a way to add proposal upload button on it cleanly. And redirect the user on first login may require changing a lot of code. Can we just put a profile link on the sidebar?
* [x]  Redirecting to /clear_accepted_proposal_pdf/ seems a really strange way to handle this, may be better to upload with ajax and return a confirm, then based on that save it if accepted, rather then redirect to a erase page.
> Added AJAX support.
* [x]  Delete does not remove it from the media folder.
> Now it does.

@botanicvelious Check this!!

**Comment by botanicvelious** [comment]
Also on the validators

```Python
>>> from django.core import validators
>>> validators.validate_email('test@example.com')
>>> validators.validate_email('test@examplecom')
Traceback (most recent call last):
   File "<console>", line 1, in <module>
   File "/Users/jasper/Sites/iaid/env/lib/python2.7/site-    packages/django/core/validators.py", line 155, in __call__
    super(EmailValidator, self).__call__(u'@'.join(parts))
  File "/Users/jasper/Sites/iaid/env/lib/python2.7/site-packages/django/core/validators.py", line 44, in __call__
    raise ValidationError(self.message, code=self.code)
ValidationError: [u'Enter a valid e-mail address.']
```

You would regex looking for a possible match with a super broad query, and then pass it to email validator to see if it is a real email. Basically a "email_search" validator. It does look like your regex currently would deal with the search part at least.

For phone numbers make a new validator https://docs.djangoproject.com/en/2.1/ref/validators/ not just a regex, as currently it only checks us numbers, a validator would allow you to add a list of checks

For example we would want to check the following regex's and more
```regex
India
(((\+){0,1}91(\s){0,1}(\-){0,1}(\s){0,1}){0,1}98(\s){0,1}(\-){0,1}(\s){0,1}[1-9]{1}[0-9]{7})
UK
(07([\d]{3})[(\D\s)]?[\d]{3}[(\D\s)]?[\d]{3})
```

**Comment by botanicvelious** [comment]
Actually no, your regex is too broad... 
```regex
([^\s]+@[^\s]+\.[^\s]+)
```
Should return all possible email's in a string, (use [findall](https://docs.python.org/3/library/re.html#re.findall) probably) then you can pass them to the emailvalidator to see if they are actually emails.

**Comment by botanicvelious** [comment]
Also would be good if the returned message to the user said what data exactly it matched, For exmaple 

>Possible personal data found, email: test@test.com, pook@pook.com phone number: 111-222-3333, 08956-444-444

this way the user can click "ok/allow" knowing what it detected so they dont just click through without thinking

Would also want to check for an address but honestly that is a bag of worms... not sure how we could go about that... but we will want to add that later as well as possibly other checks, so validators are a much better way to go.

Just had an idea, we could use https://pkgstore.datahub.io/core/world-cities/world-cities_json/data/5b3dd46ad10990bca47b04b4739a02ba/world-cities_json.json and search for the city then return a warning if we find a match. Would have to see what kinda perf this has tho, matching against 23k possible names could be a major perf problem. But step in the right direction.

For a dataset this large membership testing using set probably faster then a regex, not sure.

**Comment by ghost** [comment]
OK. Thanks for the advice. Let me try and make the validation more powerful :)

**Comment by ghost** [comment]
@botanicvelious Created a validator in models.py and it can find email addresses and international phone numbers, but is unable to find city names yet. Please help me review my code. :p

**Comment by ghost** [comment]
@botanicvelious I happen to find out that PhoneNumberMatcher will find all phone numbers even without country code! So phone finder feature is finished! :P 
But after some tests, it doesn't seem to match any less known countries' numbers like Niue numbers like +683 1234, so I'm trying to use some regex to deal with it.

**Comment by ghost** [comment]
OK. Now it finds all phone numbers!

**Comment by botanicvelious** [comment]
<Botanic> ntkomata, lookin good
<Botanic> was really fast on a test pdf i was using
<Botanic> ntkomata, only thing i would say is to make it not popup so it lets you check "dont create additional dialogs"
<Botanic> also after you upload it you can re-click upload :)
<Botanic> should prolly redirect or something with a success

**Comment by ghost** [comment]
@botanicvelious Just gave myself a day off. Thought I had such a busy week. :D I'm working on JavaScript code now. And I may be able to redirect the students by modifying django cms login function. Does it sound too hacky for you? Or do you have a better way? Otherwise I'll just add a GIANT banner :P

**Comment by botanicvelious** [comment]
Could probably use LOGIN_REDIRECT_URL and send it to a page.

**Comment by ghost** [comment]
> Could probably use LOGIN_REDIRECT_URL and send it to a page.

Yeah right! I totally forgot this setting

**Comment by ghost** [comment]
@botanicvelious All dialogs are now html tags!

**Comment by ghost** [comment]
@botanicvelious Done after-login redirect!

**Comment by botanicvelious** [comment]
Looking good, the redirect works, just make it super obvious when they don't have a proposal uploaded, like a big red box or something. That looks to be the only thing left!

**Comment by ghost** [comment]
ok done! please chk! @botanicvelious

**Comment by ghost** [comment]
@botanicvelious Fixed css with relative position! But somehow i can't login on Test-Student1 anymore....the password's been changed?

**Comment by botanicvelious** [comment]
http://127.0.0.1:8000/en/myprofile/
<Botanic> throws an error for me
<Botanic> Page not found (404)

**Review by botanicvelious — APPROVED** [review]

**Pull request merged**
