### PR TITLE
Add the feature of Scheduling emails.

### LINKED ISSUE #40: GSoC 2019 - Create scheduler build_items page
This issue is to create a page and system that allows you to select tasks to be scheduled at specific times and on specific triggers.

For date scheduling you would select a date and time, then you would select the task, the tasks would need to come from the scheduler.command model field choices as a selectbox. When build_items is run it would check this data and see if it needs to add something to the schedule model data table.

For trigger schedule, you would need to write the base code to be able to specify some logic, for example. 
>foreach user where group == student if last_blog_post > 7 days then send_email for user

That is the only trigger scheduler you need to add for now but it needs to be simple to add more. These triggers may best be done in python code and not as part of the webpage.

This system would need to be tied into the build_items part of the scheduler system, so when build_items is run it auto adds to the scheduler model data table the items as appropriate.

### PR DESCRIPTION
**Pull request by DeboDevelop**
# Description

Added the file automail.py that contain the logic to sent Emails. Also add the template task.html. From there the task can be scheduled.

Fixes #40 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Currently, it is incomplete.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have not added a commit to any .db files as part of my pull request
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by HAKSOAT** [comment]
Hello @DeboDevelop is there any additional information that you can provide to help me commence this task?

**Comment by DeboDevelop** [comment]
@HAKSOAT Wait, wait. It's not complete yet. I will try to finish emailing part tonight. Then only scheduling part will be left. I am a little busy with college task.

Which task are you talking about? Sending email?

**Comment by HAKSOAT** [comment]
@DeboDevelop Yes, I'm talking about scheduling email.

**Comment by DeboDevelop** [comment]
@HAKSOAT You are a mentor, right?
You can add an email to admin account from admin panel.
Then you can open http://127.0.0.1:8000/runtask/
and click on "Run" button.

This will sent an email aka print the email in the console.

So, the email part is done. The only part left is the scheduling with crontask part.

If you are a mentor, you can review my work and compare it against issue #40 and tell me if I did anything wrong.
If you are not a mentor then @botanicvelious  please review my work.

I know the scheduling part is still left, please bear with me as I am currently overburdened with work.

I had a few question regarding building the schedule task. Like my entire email logic is done in autoemail.py, so in build_items function, I am just suppose to check the command and call that function accordingly, right?

**Comment by HAKSOAT** [comment]
I'm not.

**Comment by DeboDevelop** [comment]
@HAKSOAT Lol. If you want to work on this issue, sorry man, I am already working on it.
You may look at other issues.

@botanicvelious Please check my PR.

**Comment by ghost** [comment]
@DeboDevelop  I wrote a mail template system and later maybe you can use my code to send emails. It can send all kinds of emails that the site needs to.

**Comment by ghost** [comment]
@DeboDevelop  Another thing! Make sure to use the `Scheduler` model.

**Comment by DeboDevelop** [comment]
@ntkomata Sorry, could not reply early.
Okay, I will look into the scheduler mode.

I will look into your mail template system later.

**Comment by botanicvelious** [comment]
When i click the button i get

```python
Quit the server with CTRL-BREAK.
INFO 2019-03-30 11:09:07,916 12220 13156 basehttp.py basehttp log_message 154 "GET /runtask/ HTTP/1.1" 200 8986
INFO 2019-03-30 11:09:07,970 12220 13156 basehttp.py basehttp log_message 154 "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 41
Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
ERROR 2019-03-30 11:09:07,970 12220 13156 basehttp.py basehttp log_message 154 "GET /static/debug_toolbar/css/print.css HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52764)
Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 116, in handle_error
    super().handle_error()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 111, in close
    super().close()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------

INFO 2019-03-30 11:09:11,095 12220 6272 basehttp.py basehttp log_message 154 "GET /runtaskoutput/ HTTP/1.1" 200 9003
```
Also it looks like you just made a page that lets you click a button to send out emails?

The following items look to be missing

- [ ] create a page and system that allows you to select tasks to be scheduled at specific times and on specific triggers.
- [ ] For date scheduling you would select a date and time, then you would select the task, the tasks would need to come from the scheduler.command model field choices as a selectbox.
- [ ] This system would need to be tied into the build_items part of the scheduler system, so when build_items is run it auto adds to the scheduler model data table the items as appropriate.

for the ui i would use somethin like [https://doxfer.webmin.com/mediawiki/images/7/73/Scheduled_Cron_Jobs_-_Edit.png](https://doxfer.webmin.com/mediawiki/images/7/73/Scheduled_Cron_Jobs_-_Edit.png)

**Comment by botanicvelious** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
