### PR TITLE
Hide and make readonly article admin fields for students.

### PR DESCRIPTION
**Pull request by ghost**
### Meta Options
* slug
* meta_title
* meta_description
* meta_keywords
### Advanced Settings
* tags
* categories
* related
* owner
## The following Article fields are readonly for students.
* author
* publishing_date
* is_featured
* featured_image
* slug

And the data will be checked or fixed using ArticleAdmin.add_view() during POST request.

### CODE REVIEW

**Comment by ghost** [comment]
@botanicvelious Please check!

**Comment by botanicvelious** [comment]
Looks good, the only issue I see is there is still a "section" box under Advanced Settings, I may have missed that one on the list

**Comment by ghost** [comment]
@botanicvelious Done! now it will automatically create articles in the first section for students.

**Comment by sounak98** [comment]
@botanicvelious why does it automatically create an article in the first section? 

And also this breaks the editing of an article by any user other than the supersurer. It says `Please correct the errors below` and doesn't show any errors (which is because some fields are hidden). a bit of debugging showed me that while editing the publishing date and time fields become empty, also the owner field is empty.

**Comment by ghost** [comment]
@sounak98 the code was a little hacky :). I'll deal with it as soon as possible

**Comment by ghost** [comment]
@sounak98  see #81

**Pull request merged**
