### PR TITLE
Add template styling

### PR DESCRIPTION
**Pull request by sounak98**
Fixes https://github.com/python-gsoc/python-blogs/issues/1
Attaching a screenshot of the navbar designed according to https://python-gsoc.org.

screenshot 2019-02-14 at 5 26 04 pm

### CODE REVIEW

**Review by dotgourav — DISMISSED** [review]
Remove the .gitignore from this PR. The change is not related to the current issue and a separate PR can be added for this.

**Comment by sounak98** [comment]
> Remove the .gitignore from this PR. The change is not related to the current issue and a separate PR can be added for this.

@Gouravchawla made the changes as requested, should I make another pull request for the `.gitignore` file?

**Comment by botanicvelious** [comment]
A few comments

1. The website uses pure.css from https://purecss.io/ so make sure you include that rather than just your own custom css.
2. Dont just stick the css in the header of the main file. You want to make a static css file and load that.

**Comment by sounak98** [comment]
@botanicvelious I was already planning on moving the css to a static file.

I have included `purecss` and also added a static file for the css and linked it to the base template in the latest commit.

**Comment by sounak98** [comment]
@botanicvelious did you check the updates?

**Comment by botanicvelious** [comment]
You might want to look at [http://python-gsoc.org/css/side-menu.css](http://python-gsoc.org/css/side-menu.css) for the sidebar css, that should help you not have to reinvent the wheel. Also [http://python-gsoc.org/css/python-gsoc.css](http://python-gsoc.org/css/python-gsoc.css) would likely be useful.

**Comment by botanicvelious** [comment]
Was posting when you replied. So I checked out the rest and the theme is still quite a bit different. Comparing the look and feel side by side there are some pretty major differences. It is a step in the right direction, however. Look at my last comment and you can see the 2 CSS files the site uses, those should help you get even closer without much extra work.

**Comment by sounak98** [comment]
Please check the pages now, exact styling has been applied as https://python-gsoc.org.

**Review by botanicvelious — CHANGES_REQUESTED** [review]
I pulled your code and it seems that it broke the menu at the top, when I click on "page", for example, nothing happens. It looks like your javascript broke the cms javascript.

**Comment by botanicvelious** [comment]
To be clear I am talking about the menu that shows up when you log in via http://127.0.0.1:8000/en/?edit

Also, it seems that even removing your custom javascript makes it still be broken. Just curious what is the point of the js that was added anyways exactly, im not entirely sure why it was added?

Lastly your js throws an error in the console

```
TypeError: content is null[Learn More] ui.js:40:5

<anonymous> http://127.0.0.1:8000/static/js/ui.js:40 
<anonymous> http://127.0.0.1:8000/static/js/ui.js:1 
```

**Comment by sounak98** [comment]
@botanicvelious my bad, the `ui.js` file was mistakenly added, because I was taking some parts of the code from the current website repo. Now everything is working perfectly. Please check once.

**Comment by botanicvelious** [comment]
the menu's are still broken on my side

**Comment by sounak98** [comment]
@botanicvelious are you talking about these?

screenshot 2019-02-15 at 1 54 50 am

screenshot 2019-02-15 at 2 11 50 am

**Comment by botanicvelious** [comment]
Yes that is correct does it work for you?

**Comment by botanicvelious** [comment]
Odd must have been some cache issue on my side, it looks to work now!

**Pull request merged**
