### PR TITLE
Moved all js from templates to .js file

### LINKED ISSUE #98: GSoC 2019 - Move js from templates to .js file
All the js should be moved to .js files not be in the templates

### PR DESCRIPTION
**Pull request by sharmaadityaHQ**
# Description

All js code has been moved to .js files.
Fixes #98

### CODE REVIEW

**Comment by sharmaadityaHQ** [comment]
Please have a look at this @botanicvelious .

**Comment by botanicvelious** [comment]
Looks like only js from djangocms_text_ckeditor however that is an external plugin, it is best to leave that stuff alone, we only need to move the js for the gsoc site itself.

**Comment by sharmaadityaHQ** [comment]
Ok I'll fix this up.

**Comment by sounak98** [comment]
@botanicvelious this is done by #139, can be closed.

**Pull request closed without merging**
