### PR TITLE
Revamp UI

### LINKED ISSUE #83: UI inconsistencies
Some UI elements of the website are inconsistent. These examples will help understanding them better.

- The top bar is not fixed to the top and the height doesn't match.
Screenshot 2019-03-27 at 2 13 03 PM

- In mobile view the top bar breaks and also it is impossible to access the menu. 
Screenshot 2019-03-27 at 2 13 25 PM

- The notifications on the top goes below the sidebar.
Screenshot 2019-03-27 at 2 13 56 PM

These can be fixed to get a responsive and clean UI.

### PR DESCRIPTION
**Pull request by sounak98**
# Description

Fixes #83 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Screenshots

- Fixed the top navigation bar
Screenshot 2019-03-27 at 2 26 11 PM

- Mobile view
Screenshot 2019-03-27 at 2 26 22 PM

- Clicking on the hamburger icon toggles the menu
Screenshot 2019-03-27 at 2 26 28 PM

- Notification boxes
Screenshot 2019-03-27 at 2 26 44 PM

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have not added a commit to any .db files as part of my pull request
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sounak98** [comment]
@botanicvelious check this once you're back!

**Comment by sounak98** [comment]
Also changed the blog views a bit.

- List view
Screenshot 2019-03-27 at 2 32 11 PM

- Detail view
Screenshot 2019-03-27 at 2 32 24 PM

- No blogs
Screenshot 2019-03-27 at 2 32 31 PM

**Comment by botanicvelious** [comment]
The ui breaks between mobile and widescreen, no menu and the login bar is wack.

It looks like you didn't really use pure.css using pure.css would save you a lot of work, especially with cross-browser stuff.

**Comment by sounak98** [comment]
@botanicvelious ui doesn't break anymore and I have used pure.css classes to create the top navbar

**Comment by botanicvelious** [comment]
Looks better I will create a issue for redoing the css as needed with pure.css there is still stuff in here that could use pure but some is from like newsblog so fixing all of it will be a bit of a larger task.

**Pull request merged**
