### PR TITLE
#52 Theme for student-blog

### PR DESCRIPTION
**Pull request by MastersAbh**
I have organized the articles displayed on the blog page of an user.

### CODE REVIEW

**Comment by MastersAbh** [comment]
@botanicvelious please give your comments if the functionality is as required.

**Comment by botanicvelious** [comment]
Conflicting files
gsoc/views.py

Please fix so I can check it

**Comment by MastersAbh** [comment]
It shows views.py as conflicting files. I don't understand why. It doesn't even exist in the repo. I guess somebody deleted the file in their commit. It was there in my last commit.

**Comment by botanicvelious** [comment]
update your local git to the repo and that should resolve it then

**Comment by MastersAbh** [comment]
@botanicvelious do check

**Comment by botanicvelious** [comment]
<Botanic> masters_abh[m], https://filebin.net/9blg2d01n105pa26
<Botanic> download and run that database
<Botanic> then goto test
<Botanic> it needs work
<Botanic> not sure why student blogs works differently?
<Botanic> maby it was setup wrong or broken somehow...

**Comment by botanicvelious** [comment]
Also for the title on the top of the page for the blog put the name of the page

**Comment by MastersAbh** [comment]
Please review @botanicvelious

**Comment by botanicvelious** [comment]
For the blog it says "By 1 on March 8, 2019" rather then the username.

Other then that looks good.

**Comment by MastersAbh** [comment]
I used article.author only. Seems that the author is 1

**Comment by MastersAbh** [comment]
article.owner would show "admin". Should use that ?

**Comment by botanicvelious** [comment]
Yes 1 is the user id not the name :)

**Comment by MastersAbh** [comment]
Ohh the author/owner words were confusing. Done that @botanicvelious

**Pull request merged**
