### PR TITLE
Add preconfiguration fields for RegLink and fix css

### PR DESCRIPTION
**Pull request by ghost**
## RegLink
* Create following fields for RegLink so that it can be preconfigured to register customized user 

user role

user suborg

user gsoc year

FireShot Capture 001 - Change reg link - Django site admin - localhost

* These preconfiguration fields will be made readonly when the user's been registered.

FireShot Capture 002 - Change reg link - Django site admin - localhost

## CSS fix
Fix myprofile.html and register.html and now their content won't be covered by the left sidebar.

# DB
DB not migrated yet.

### CODE REVIEW

**Comment by ghost** [comment]
@botanicvelious Please check! :D

**Comment by botanicvelious** [comment]
my laptop decided to die and I am out of town for a week or so I can check this when I get back =/

**Comment by ghost** [comment]
emmK no problem

**Comment by botanicvelious** [comment]
looks good

**Pull request merged**
