### PR TITLE
Deactivation user

### LINKED ISSUE #66: GSoC 2019 - Auto disable users
This issue is to add a feature so that you can set a date that the user will automatically have there account "active" status disabled. The date would be set in the user Home › Authentication and Authorization › Users › Test-Student1 and the check could be done as part of the run_cron command.

### PR DESCRIPTION
**Pull request by sounak98**
# Description

This adds a new runcron process which will deactivate a user on a certain date and time. Helps in deactivating users after the current GSoC period.

Fixes #66 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Had added the deactivation date for a UserProfile in the admin panel and the user got deactivated when the `runcron process_items` was run after the scheduled date and time

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have not added a commit to any .db files as part of my pull request
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by botanicvelious** [comment]
- [ ] This branch has conflicts that must be resolved
- [ ] I don't see any code for the admin page to let you set the date to deactivate the user.

**Comment by sounak98** [comment]
https://github.com/python-gsoc/python-blogs/pull/71/commits/178ab89735c3aaef91f97c3e7ccafb4bbfd932c8#diff-663dbff8f9c23aa31f98584578a8959fR7

@botanicvelious this is the part which incorporates the date field in the UserProfile form in the admin panel. Also the merge conflicts have been resolved.

**Comment by botanicvelious** [comment]
So it looks like you applied this to the userprofile objects which made it so that the admin page now has User profile: UserProfile object (1) User profile: UserProfile object (2) etc. The deactivate should be done on the user, not per object.

**Comment by sounak98** [comment]
Oh okay, I'll change it to the user rather than on the UserProfile.

**Pull request merged**
