### PR TITLE
Added red box at the top of unpublished pages.

### PR DESCRIPTION
**Pull request by Saurabh-Singh-00**
# Description
A red box is added at the top of unpublished page. This red box is visible to only admin if he/she has created the page but has not published it. The changes are made in base.html because every page created extends this template.

Fixes # (issue) #53 

- [x] Added red box at the top if page is unpublished.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have not added a commit to any .db files as part of my pull request

### CODE REVIEW

**Comment by botanicvelious** [comment]
Using your code I dont see a message, https://i.imgur.com/kwkDBkp.png

**Comment by Saurabh-Singh-00** [comment]
@botanicvelious I will have a look at it. Please lend me some time.

**Comment by Saurabh-Singh-00** [comment]
@botanicvelious I have updated the code please have a look at it.

**Comment by botanicvelious** [comment]
so I see https://i.imgur.com/aGLZT9Y.png it looks like there is a red box but no message or otherwise.

**Comment by Saurabh-Singh-00** [comment]
Like? if you need any specific text I can accommodate in that red box. But the core functionality is achieved, right? Do I need to do something more?

**Comment by botanicvelious** [comment]
The task is to

>This task is to add a notice to a logged in user when a page is unpublished. Some sort of large red box at the top would do nicely.

The point of the task is to show a message so that it is obvious when a page is not published.

**Comment by Saurabh-Singh-00** [comment]
Screenshot from 2019-03-13 15-01-56

Is this ok?

**Pull request merged**
