### PR TITLE
Add Comments to Articles

### LINKED ISSUE #51: GSoC 2019 - Add user comments
This task is to add a form to the bottom of a blog page that allows a logged in user to comment.

### PR DESCRIPTION
**Pull request by sounak98**
# Description

Adds commenting feature to the articles in the blogs
Fixes #51 

## Beahviour

- Shows the form to add a root comment
- On clicking a reply button on a comment, it opens up a new form for replying to that comment

## Todo

- [x] Add reCAPTCHA verification
- [x] Block abusive language
- [ ] Add reactions (or just like, dislike?) 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Screenshot(s)

Screenshot from 2019-05-05 15-04-40

# Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have not added a commit to any .db files as part of my pull request
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sounak98** [comment]
@botanicvelious let me know if you feel there are changes that needs to be made.

**Comment by botanicvelious** [comment]
1. First the code style stuff 👍 
2. For posting as an anon user would be nice if it let you use facebook/google login, maby even require a login via the site, google, or facebook, so that there isnt spam if they dont do a reCAPTCHA?
3. Adding a "share" button would be nice that auto takes you to the comment
4. Posts should have a date
5. What is that "hello" user link on the top comment?
6. "Add reactions (or just like, dislike?)" Dunno if this is really appropriate as this is for students and don't want to have people trolling

**Comment by sounak98** [comment]
@botanicvelious basically the hello is not a link, when a user is not signed in, the form asks you for a username to display too, I had put it as `hello`.

Also,
1. I will add a share button that will copy the link to the comment
2. I'll add date to the posts
3. And the code style stuff goes without saying

Do we need reCAPTCHA if there is a login (via Google, Facebook or anything)? Or we give an option to either login via one of these for use reCAPTCHA?

**Comment by botanicvelious** [comment]
id say only need reCAPTCHA if anon

**Comment by sounak98** [comment]
@botanicvelious currently these sample comments are added to the db. Also, share button copies the link to the comment in the clipboard. Invisible reCAPTCHA and profanity filter have also been added.

Do check and let me know!

Screenshot 2019-05-08 at 2 42 11 PM

**Pull request merged**
